/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Wed Aug 19 10:28:31 IST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTrafficLight.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTrafficLight::MODEL_mkTrafficLight()
{
  mkTrafficLight_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTrafficLight()
{
  MODEL_mkTrafficLight *model = new MODEL_mkTrafficLight();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTrafficLight &INST_top = *((MOD_mkTrafficLight *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_tick;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_tick;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_show;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_show;
	 INST_top.DEF_b__h229 = INST_top.INST_count.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_show = (INST_top.DEF_b__h229) < (tUInt8)6u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_show = DEF_INST_top_DEF_CAN_FIRE_RL_show;
	 DEF_INST_top_DEF_CAN_FIRE_RL_tick = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_tick = DEF_INST_top_DEF_CAN_FIRE_RL_tick;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_tick)
	   INST_top.RL_tick();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_show)
	   INST_top.RL_show();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_state.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_count.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTrafficLight::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTrafficLight_instance = new MOD_mkTrafficLight(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTrafficLight_instance->set_clk_0)("CLK");
}
void MODEL_mkTrafficLight::destroy_model()
{
  delete mkTrafficLight_instance;
  mkTrafficLight_instance = NULL;
}
void MODEL_mkTrafficLight::reset_model(bool asserted)
{
  (mkTrafficLight_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTrafficLight::get_instance()
{
  return mkTrafficLight_instance;
}

/* Fill in version numbers */
void MODEL_mkTrafficLight::get_version(char const **name, char const **build)
{
  *name = "2025.01.1";
  *build = "65e3a87a";
}

/* Get the model creation time */
time_t MODEL_mkTrafficLight::get_creation_time()
{
  
  /* Wed Aug 19 04:58:31 UTC 2026 */
  return 1787115511llu;
}

/* State dumping function */
void MODEL_mkTrafficLight::dump_state()
{
  (mkTrafficLight_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTrafficLight & mkTrafficLight_backing(tSimStateHdl simHdl)
{
  static MOD_mkTrafficLight *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTrafficLight(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTrafficLight::dump_VCD_defs()
{
  (mkTrafficLight_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTrafficLight::dump_VCD(tVCDDumpType dt)
{
  (mkTrafficLight_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTrafficLight_backing(sim_hdl));
}
