/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Wed Aug 19 13:21:05 IST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "mkProducerConsumer.h"


/* String declarations */
static std::string const __str_literal_2("Consumed %0d, Square = %0d", 26u);
static std::string const __str_literal_1("Produced %0d", 12u);


/* Constructor */
MOD_mkProducerConsumer::MOD_mkProducerConsumer(tSimStateHdl simHdl,
					       char const *name,
					       Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_count(simHdl, "count", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_data(simHdl, "data", this, 8u, (tUInt8)1u, (tUInt8)0u),
    INST_fifo(simHdl, "fifo", this, 8u, 2u, (tUInt8)1u, 0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 8u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkProducerConsumer::init_symbols_0()
{
  init_symbol(&symbols[0u], "b__h196", SYM_DEF, &DEF_b__h196, 8u);
  init_symbol(&symbols[1u], "b__h366", SYM_DEF, &DEF_b__h366, 8u);
  init_symbol(&symbols[2u], "count", SYM_MODULE, &INST_count);
  init_symbol(&symbols[3u], "data", SYM_MODULE, &INST_data);
  init_symbol(&symbols[4u], "fifo", SYM_MODULE, &INST_fifo);
  init_symbol(&symbols[5u], "RL_consumer", SYM_RULE);
  init_symbol(&symbols[6u], "RL_producer", SYM_RULE);
  init_symbol(&symbols[7u], "RL_stop", SYM_RULE);
}


/* Rule actions */

void MOD_mkProducerConsumer::RL_producer()
{
  tUInt8 DEF_data_PLUS_1___d6;
  tUInt8 DEF_unsigned_data___d5;
  DEF_b__h196 = INST_data.METH_read();
  DEF_unsigned_data___d5 = DEF_b__h196;
  DEF_data_PLUS_1___d6 = (tUInt8)255u & (DEF_b__h196 + (tUInt8)1u);
  INST_fifo.METH_enq(DEF_b__h196);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,8", &__str_literal_1, DEF_unsigned_data___d5);
  INST_data.METH_write(DEF_data_PLUS_1___d6);
}

void MOD_mkProducerConsumer::RL_consumer()
{
  tUInt8 DEF_count_4_PLUS_1___d15;
  tUInt32 DEF__0_CONCAT_fifo_first___d10;
  tUInt8 DEF_fifo_first____d8;
  tUInt8 DEF_unsigned_fifo_first___d9;
  tUInt32 DEF_unsigned_0_CONCAT_fifo_first_0_MUL_0_CONCAT_f_ETC___d13;
  DEF_fifo_first____d8 = INST_fifo.METH_first();
  DEF_unsigned_fifo_first___d9 = DEF_fifo_first____d8;
  DEF_b__h366 = INST_count.METH_read();
  DEF__0_CONCAT_fifo_first___d10 = 65535u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_fifo_first____d8));
  DEF_unsigned_0_CONCAT_fifo_first_0_MUL_0_CONCAT_f_ETC___d13 = (tUInt32)(65535u & (DEF__0_CONCAT_fifo_first___d10 * DEF__0_CONCAT_fifo_first___d10));
  DEF_count_4_PLUS_1___d15 = (tUInt8)255u & (DEF_b__h366 + (tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl,
		   this,
		   "s,8,16",
		   &__str_literal_2,
		   DEF_unsigned_fifo_first___d9,
		   DEF_unsigned_0_CONCAT_fifo_first_0_MUL_0_CONCAT_f_ETC___d13);
  INST_fifo.METH_deq();
  INST_count.METH_write(DEF_count_4_PLUS_1___d15);
}

void MOD_mkProducerConsumer::RL_stop()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_finish(sim_hdl, "32", 1u);
}


/* Methods */


/* Reset routines */

void MOD_mkProducerConsumer::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_fifo.reset_RST(ARG_rst_in);
  INST_data.reset_RST(ARG_rst_in);
  INST_count.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkProducerConsumer::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkProducerConsumer::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_count.dump_state(indent + 2u);
  INST_data.dump_state(indent + 2u);
  INST_fifo.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkProducerConsumer::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 6u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h196", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h366", 8u);
  num = INST_count.dump_VCD_defs(num);
  num = INST_data.dump_VCD_defs(num);
  num = INST_fifo.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkProducerConsumer::dump_VCD(tVCDDumpType dt,
				      unsigned int levels,
				      MOD_mkProducerConsumer &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkProducerConsumer::vcd_defs(tVCDDumpType dt, MOD_mkProducerConsumer &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_b__h196) != DEF_b__h196)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h196, 8u);
	backing.DEF_b__h196 = DEF_b__h196;
      }
      ++num;
      if ((backing.DEF_b__h366) != DEF_b__h366)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h366, 8u);
	backing.DEF_b__h366 = DEF_b__h366;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_b__h196, 8u);
      backing.DEF_b__h196 = DEF_b__h196;
      vcd_write_val(sim_hdl, num++, DEF_b__h366, 8u);
      backing.DEF_b__h366 = DEF_b__h366;
    }
}

void MOD_mkProducerConsumer::vcd_prims(tVCDDumpType dt, MOD_mkProducerConsumer &backing)
{
  INST_count.dump_VCD(dt, backing.INST_count);
  INST_data.dump_VCD(dt, backing.INST_data);
  INST_fifo.dump_VCD(dt, backing.INST_fifo);
}
