/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Wed Aug 19 13:21:05 IST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkProducerConsumer.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkProducerConsumer::MODEL_mkProducerConsumer()
{
  mkProducerConsumer_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkProducerConsumer()
{
  MODEL_mkProducerConsumer *model = new MODEL_mkProducerConsumer();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkProducerConsumer &INST_top = *((MOD_mkProducerConsumer *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_producer;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_producer;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_consumer;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_consumer;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_stop;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_stop;
	 DEF_INST_top_DEF_CAN_FIRE_RL_consumer = INST_top.INST_fifo.METH_i_notEmpty();
	 DEF_INST_top_DEF_WILL_FIRE_RL_consumer = DEF_INST_top_DEF_CAN_FIRE_RL_consumer;
	 INST_top.DEF_b__h196 = INST_top.INST_data.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_producer = INST_top.INST_fifo.METH_i_notFull() && (INST_top.DEF_b__h196) <= (tUInt8)10u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_producer = DEF_INST_top_DEF_CAN_FIRE_RL_producer;
	 INST_top.DEF_b__h366 = INST_top.INST_count.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_stop = (INST_top.DEF_b__h366) == (tUInt8)10u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_stop = DEF_INST_top_DEF_CAN_FIRE_RL_stop;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_producer)
	   INST_top.RL_producer();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_stop)
	   INST_top.RL_stop();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_consumer)
	   INST_top.RL_consumer();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_data.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_count.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkProducerConsumer::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkProducerConsumer_instance = new MOD_mkProducerConsumer(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkProducerConsumer_instance->INST_fifo.set_clk_0)("CLK");
  (mkProducerConsumer_instance->set_clk_0)("CLK");
}
void MODEL_mkProducerConsumer::destroy_model()
{
  delete mkProducerConsumer_instance;
  mkProducerConsumer_instance = NULL;
}
void MODEL_mkProducerConsumer::reset_model(bool asserted)
{
  (mkProducerConsumer_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkProducerConsumer::get_instance()
{
  return mkProducerConsumer_instance;
}

/* Fill in version numbers */
void MODEL_mkProducerConsumer::get_version(char const **name, char const **build)
{
  *name = "2025.01.1";
  *build = "65e3a87a";
}

/* Get the model creation time */
time_t MODEL_mkProducerConsumer::get_creation_time()
{
  
  /* Wed Aug 19 07:51:05 UTC 2026 */
  return 1787125865llu;
}

/* State dumping function */
void MODEL_mkProducerConsumer::dump_state()
{
  (mkProducerConsumer_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkProducerConsumer & mkProducerConsumer_backing(tSimStateHdl simHdl)
{
  static MOD_mkProducerConsumer *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkProducerConsumer(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkProducerConsumer::dump_VCD_defs()
{
  (mkProducerConsumer_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkProducerConsumer::dump_VCD(tVCDDumpType dt)
{
  (mkProducerConsumer_instance->dump_VCD)(dt,
					  vcd_depth(sim_hdl),
					  mkProducerConsumer_backing(sim_hdl));
}
