/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Wed Jul  8 14:50:13 IST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkToggle.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkToggle::MODEL_mkToggle()
{
  mkToggle_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkToggle()
{
  MODEL_mkToggle *model = new MODEL_mkToggle();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkToggle &INST_top = *((MOD_mkToggle *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_do_incr;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_do_incr;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_do_decr;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_do_decr;
	 INST_top.DEF_b__h78 = INST_top.INST_count.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_do_incr = (INST_top.DEF_b__h78) < (tUInt8)10u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_do_incr = DEF_INST_top_DEF_CAN_FIRE_RL_do_incr;
	 DEF_INST_top_DEF_CAN_FIRE_RL_do_decr = !((INST_top.DEF_b__h78) == (tUInt8)0u);
	 DEF_INST_top_DEF_WILL_FIRE_RL_do_decr = DEF_INST_top_DEF_CAN_FIRE_RL_do_decr && !DEF_INST_top_DEF_WILL_FIRE_RL_do_incr;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_do_decr)
	   INST_top.RL_do_decr();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_do_incr)
	   INST_top.RL_do_incr();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_count.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkToggle::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkToggle_instance = new MOD_mkToggle(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkToggle_instance->set_clk_0)("CLK");
}
void MODEL_mkToggle::destroy_model()
{
  delete mkToggle_instance;
  mkToggle_instance = NULL;
}
void MODEL_mkToggle::reset_model(bool asserted)
{
  (mkToggle_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkToggle::get_instance()
{
  return mkToggle_instance;
}

/* Fill in version numbers */
void MODEL_mkToggle::get_version(char const **name, char const **build)
{
  *name = "2025.01.1";
  *build = "65e3a87a";
}

/* Get the model creation time */
time_t MODEL_mkToggle::get_creation_time()
{
  
  /* Wed Jul  8 09:20:13 UTC 2026 */
  return 1783502413llu;
}

/* State dumping function */
void MODEL_mkToggle::dump_state()
{
  (mkToggle_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkToggle & mkToggle_backing(tSimStateHdl simHdl)
{
  static MOD_mkToggle *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkToggle(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkToggle::dump_VCD_defs()
{
  (mkToggle_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkToggle::dump_VCD(tVCDDumpType dt)
{
  (mkToggle_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkToggle_backing(sim_hdl));
}
