/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Wed Jul  8 16:01:27 IST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "mkSwap.h"


/* String declarations */
static std::string const __str_literal_1("Before swap: a=%0d b=%0d", 24u);


/* Constructor */
MOD_mkSwap::MOD_mkSwap(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_a(simHdl, "a", this, 8u, (tUInt8)5u, (tUInt8)0u),
    INST_b(simHdl, "b", this, 8u, (tUInt8)9u, (tUInt8)0u),
    INST_cycle(simHdl, "cycle", this, 8u, (tUInt8)0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 5u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkSwap::init_symbols_0()
{
  init_symbol(&symbols[0u], "a", SYM_MODULE, &INST_a);
  init_symbol(&symbols[1u], "b", SYM_MODULE, &INST_b);
  init_symbol(&symbols[2u], "cycle", SYM_MODULE, &INST_cycle);
  init_symbol(&symbols[3u], "RL_stop", SYM_RULE);
  init_symbol(&symbols[4u], "RL_swap", SYM_RULE);
}


/* Rule actions */

void MOD_mkSwap::RL_swap()
{
  tUInt8 DEF_b__h168;
  tUInt8 DEF_unsigned_b___d4;
  tUInt8 DEF_b__h165;
  tUInt8 DEF_unsigned_a___d2;
  DEF_b__h165 = INST_a.METH_read();
  DEF_unsigned_a___d2 = DEF_b__h165;
  DEF_b__h168 = INST_b.METH_read();
  DEF_unsigned_b___d4 = DEF_b__h168;
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,8,8", &__str_literal_1, DEF_unsigned_a___d2, DEF_unsigned_b___d4);
  INST_a.METH_write(DEF_b__h168);
  INST_b.METH_write(DEF_b__h165);
}

void MOD_mkSwap::RL_stop()
{
  tUInt8 DEF_cycle_PLUS_1___d6;
  tUInt8 DEF_cycle_EQ_5___d7;
  tUInt8 DEF_b__h242;
  DEF_b__h242 = INST_cycle.METH_read();
  DEF_cycle_EQ_5___d7 = DEF_b__h242 == (tUInt8)5u;
  DEF_cycle_PLUS_1___d6 = (tUInt8)255u & (DEF_b__h242 + (tUInt8)1u);
  INST_cycle.METH_write(DEF_cycle_PLUS_1___d6);
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_cycle_EQ_5___d7)
      dollar_finish(sim_hdl, "32", 1u);
}


/* Methods */


/* Reset routines */

void MOD_mkSwap::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_cycle.reset_RST(ARG_rst_in);
  INST_b.reset_RST(ARG_rst_in);
  INST_a.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkSwap::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkSwap::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_a.dump_state(indent + 2u);
  INST_b.dump_state(indent + 2u);
  INST_cycle.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkSwap::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 4u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  num = INST_a.dump_VCD_defs(num);
  num = INST_b.dump_VCD_defs(num);
  num = INST_cycle.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkSwap::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkSwap &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkSwap::vcd_defs(tVCDDumpType dt, MOD_mkSwap &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
    }
}

void MOD_mkSwap::vcd_prims(tVCDDumpType dt, MOD_mkSwap &backing)
{
  INST_a.dump_VCD(dt, backing.INST_a);
  INST_b.dump_VCD(dt, backing.INST_b);
  INST_cycle.dump_VCD(dt, backing.INST_cycle);
}
