/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Wed Jul  8 16:01:27 IST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkSwap.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkSwap::MODEL_mkSwap()
{
  mkSwap_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkSwap()
{
  MODEL_mkSwap *model = new MODEL_mkSwap();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkSwap &INST_top = *((MOD_mkSwap *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_swap;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_swap;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_stop;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_stop;
	 DEF_INST_top_DEF_CAN_FIRE_RL_stop = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_stop = DEF_INST_top_DEF_CAN_FIRE_RL_stop;
	 DEF_INST_top_DEF_CAN_FIRE_RL_swap = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_swap = DEF_INST_top_DEF_CAN_FIRE_RL_swap;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_swap)
	   INST_top.RL_swap();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_stop)
	   INST_top.RL_stop();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_a.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_b.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_cycle.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkSwap::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkSwap_instance = new MOD_mkSwap(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkSwap_instance->set_clk_0)("CLK");
}
void MODEL_mkSwap::destroy_model()
{
  delete mkSwap_instance;
  mkSwap_instance = NULL;
}
void MODEL_mkSwap::reset_model(bool asserted)
{
  (mkSwap_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkSwap::get_instance()
{
  return mkSwap_instance;
}

/* Fill in version numbers */
void MODEL_mkSwap::get_version(char const **name, char const **build)
{
  *name = "2025.01.1";
  *build = "65e3a87a";
}

/* Get the model creation time */
time_t MODEL_mkSwap::get_creation_time()
{
  
  /* Wed Jul  8 10:31:27 UTC 2026 */
  return 1783506687llu;
}

/* State dumping function */
void MODEL_mkSwap::dump_state()
{
  (mkSwap_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkSwap & mkSwap_backing(tSimStateHdl simHdl)
{
  static MOD_mkSwap *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkSwap(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkSwap::dump_VCD_defs()
{
  (mkSwap_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkSwap::dump_VCD(tVCDDumpType dt)
{
  (mkSwap_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkSwap_backing(sim_hdl));
}
