/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Wed Aug 19 15:01:02 IST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "mkRulepriority.h"


/* String declarations */
static std::string const __str_literal_2("Decrement Rule fired: Count=%0d", 31u);
static std::string const __str_literal_1("Increment Rule fired: Count=%0d", 31u);


/* Constructor */
MOD_mkRulepriority::MOD_mkRulepriority(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_count(simHdl, "count", this, 8u, (tUInt8)0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 5u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkRulepriority::init_symbols_0()
{
  init_symbol(&symbols[0u], "b__h78", SYM_DEF, &DEF_b__h78, 8u);
  init_symbol(&symbols[1u], "count", SYM_MODULE, &INST_count);
  init_symbol(&symbols[2u], "RL_do_decr", SYM_RULE);
  init_symbol(&symbols[3u], "RL_do_incr", SYM_RULE);
  init_symbol(&symbols[4u], "RL_stop", SYM_RULE);
}


/* Rule actions */

void MOD_mkRulepriority::RL_do_incr()
{
  tUInt8 DEF_count_PLUS_1___d3;
  DEF_b__h78 = INST_count.METH_read();
  DEF_unsigned_count___d4 = DEF_b__h78;
  DEF_count_PLUS_1___d3 = (tUInt8)255u & (DEF_b__h78 + (tUInt8)1u);
  INST_count.METH_write(DEF_count_PLUS_1___d3);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,8", &__str_literal_1, DEF_unsigned_count___d4);
}

void MOD_mkRulepriority::RL_do_decr()
{
  tUInt8 DEF_count_MINUS_1___d7;
  DEF_b__h78 = INST_count.METH_read();
  DEF_unsigned_count___d4 = DEF_b__h78;
  DEF_count_MINUS_1___d7 = (tUInt8)255u & (DEF_b__h78 - (tUInt8)1u);
  INST_count.METH_write(DEF_count_MINUS_1___d7);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,8", &__str_literal_2, DEF_unsigned_count___d4);
}

void MOD_mkRulepriority::RL_stop()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_finish(sim_hdl, "32", 1u);
}


/* Methods */


/* Reset routines */

void MOD_mkRulepriority::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_count.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkRulepriority::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkRulepriority::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_count.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkRulepriority::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 4u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h78", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "unsigned_count___d4", 8u);
  num = INST_count.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkRulepriority::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkRulepriority &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkRulepriority::vcd_defs(tVCDDumpType dt, MOD_mkRulepriority &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_b__h78) != DEF_b__h78)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h78, 8u);
	backing.DEF_b__h78 = DEF_b__h78;
      }
      ++num;
      if ((backing.DEF_unsigned_count___d4) != DEF_unsigned_count___d4)
      {
	vcd_write_val(sim_hdl, num, DEF_unsigned_count___d4, 8u);
	backing.DEF_unsigned_count___d4 = DEF_unsigned_count___d4;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_b__h78, 8u);
      backing.DEF_b__h78 = DEF_b__h78;
      vcd_write_val(sim_hdl, num++, DEF_unsigned_count___d4, 8u);
      backing.DEF_unsigned_count___d4 = DEF_unsigned_count___d4;
    }
}

void MOD_mkRulepriority::vcd_prims(tVCDDumpType dt, MOD_mkRulepriority &backing)
{
  INST_count.dump_VCD(dt, backing.INST_count);
}
