/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Wed Aug 19 10:28:31 IST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "mkTrafficLight.h"


/* String declarations */
static std::string const __str_literal_6("\n", 1u);
static std::string const __str_literal_5("BLINK", 5u);
static std::string const __str_literal_1("Current state= ", 15u);
static std::string const __str_literal_3("GREEN", 5u);
static std::string const __str_literal_2("RED", 3u);
static std::string const __str_literal_4("YELLOW", 6u);


/* Constructor */
MOD_mkTrafficLight::MOD_mkTrafficLight(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_count(simHdl, "count", this, 6u, (tUInt8)0u, (tUInt8)0u),
    INST_state(simHdl, "state", this, 2u, (tUInt8)0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 5u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTrafficLight::init_symbols_0()
{
  init_symbol(&symbols[0u], "b__h229", SYM_DEF, &DEF_b__h229, 6u);
  init_symbol(&symbols[1u], "count", SYM_MODULE, &INST_count);
  init_symbol(&symbols[2u], "RL_show", SYM_RULE);
  init_symbol(&symbols[3u], "RL_tick", SYM_RULE);
  init_symbol(&symbols[4u], "state", SYM_MODULE, &INST_state);
}


/* Rule actions */

void MOD_mkTrafficLight::RL_tick()
{
  tUInt8 DEF_NOT_state_EQ_0_AND_NOT_state_EQ_1_AND_NOT_stat_ETC___d9;
  tUInt8 DEF_state_EQ_1___d3;
  tUInt8 DEF_state_EQ_0___d2;
  tUInt8 DEF_IF_state_EQ_0_THEN_2_ELSE_IF_state_EQ_1_THEN_0_ETC___d14;
  tUInt8 DEF_state_EQ_2___d4;
  tUInt8 DEF_x__h151;
  DEF_x__h151 = INST_state.METH_read();
  DEF_state_EQ_2___d4 = DEF_x__h151 == (tUInt8)2u;
  switch (DEF_x__h151) {
  case (tUInt8)0u:
    DEF_IF_state_EQ_0_THEN_2_ELSE_IF_state_EQ_1_THEN_0_ETC___d14 = (tUInt8)2u;
    break;
  case (tUInt8)1u:
    DEF_IF_state_EQ_0_THEN_2_ELSE_IF_state_EQ_1_THEN_0_ETC___d14 = (tUInt8)0u;
    break;
  case (tUInt8)2u:
    DEF_IF_state_EQ_0_THEN_2_ELSE_IF_state_EQ_1_THEN_0_ETC___d14 = (tUInt8)3u;
    break;
  default:
    DEF_IF_state_EQ_0_THEN_2_ELSE_IF_state_EQ_1_THEN_0_ETC___d14 = (tUInt8)1u;
  }
  DEF_state_EQ_0___d2 = DEF_x__h151 == (tUInt8)0u;
  DEF_state_EQ_1___d3 = DEF_x__h151 == (tUInt8)1u;
  DEF_NOT_state_EQ_0_AND_NOT_state_EQ_1_AND_NOT_stat_ETC___d9 = !DEF_state_EQ_0___d2 && (!DEF_state_EQ_1___d3 && !DEF_state_EQ_2___d4);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    dollar_write(sim_hdl, this, "s", &__str_literal_1);
    if (DEF_state_EQ_0___d2)
      dollar_write(sim_hdl, this, "s", &__str_literal_2);
    if (DEF_state_EQ_1___d3)
      dollar_write(sim_hdl, this, "s", &__str_literal_3);
    if (DEF_state_EQ_2___d4)
      dollar_write(sim_hdl, this, "s", &__str_literal_4);
    if (DEF_NOT_state_EQ_0_AND_NOT_state_EQ_1_AND_NOT_stat_ETC___d9)
      dollar_write(sim_hdl, this, "s", &__str_literal_5);
    dollar_write(sim_hdl, this, "s", &__str_literal_6);
  }
  INST_state.METH_write(DEF_IF_state_EQ_0_THEN_2_ELSE_IF_state_EQ_1_THEN_0_ETC___d14);
}

void MOD_mkTrafficLight::RL_show()
{
  tUInt8 DEF_count_5_PLUS_1___d17;
  tUInt8 DEF_count_5_EQ_5___d18;
  DEF_b__h229 = INST_count.METH_read();
  DEF_count_5_EQ_5___d18 = DEF_b__h229 == (tUInt8)5u;
  DEF_count_5_PLUS_1___d17 = (tUInt8)63u & (DEF_b__h229 + (tUInt8)1u);
  INST_count.METH_write(DEF_count_5_PLUS_1___d17);
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_count_5_EQ_5___d18)
      dollar_finish(sim_hdl, "32", 1u);
}


/* Methods */


/* Reset routines */

void MOD_mkTrafficLight::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_state.reset_RST(ARG_rst_in);
  INST_count.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTrafficLight::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTrafficLight::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_count.dump_state(indent + 2u);
  INST_state.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTrafficLight::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 4u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h229", 6u);
  num = INST_count.dump_VCD_defs(num);
  num = INST_state.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTrafficLight::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTrafficLight &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkTrafficLight::vcd_defs(tVCDDumpType dt, MOD_mkTrafficLight &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 6u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_b__h229) != DEF_b__h229)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h229, 6u);
	backing.DEF_b__h229 = DEF_b__h229;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_b__h229, 6u);
      backing.DEF_b__h229 = DEF_b__h229;
    }
}

void MOD_mkTrafficLight::vcd_prims(tVCDDumpType dt, MOD_mkTrafficLight &backing)
{
  INST_count.dump_VCD(dt, backing.INST_count);
  INST_state.dump_VCD(dt, backing.INST_state);
}
